---
- name: A simple file playbook to bind together Jenkins skills
  hosts: fry

  tasks:
   # make a directory called ~/onering/
   - name: make a directory
     file:
       path: ~/onering/
       state: directory

   # create a file torulethemall.txt within ~/onering/
   - name: make a file
     file:
       path: ~/onering/torulethemall.txt
       state: touch
