---
- name: A simple file playbook to bind together Jenkins skills
  hosts: localhost
  connection: local

  tasks:
   # make a directory called ~/onering/
   - name: make a directory
     file:
       path: /tmp/onering/
       state: directory

   # create a file torulethemall.txt within ~/onering/
   - name: make a file
     file:
       path: /tmp/onering/torulethemall.txt
       state: touch
       
   # create a file andinthedarkness.txt within ~/onering/
   - name: make a file
     file:
       path: /tmp/onering/andinthedarkness.txt
       state: touch


   # create a file bindthem.txt within ~/onering/
   - name: make a file
     file:
       path: /tmp/onering/bindthem.txt
       state: touch
